language: node_js
node_js:
  - "10"
services:
  - docker
cache:
  yarn: true
  directories:
    - node_modules

# install current version of yarn
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"

jobs:
  include:
    - stage: Test and Build
      script:
      - yarn install --frozen-lockfile --non-interactive
      - yarn run ci
    - script:
      - docker build --build-arg BUILD_COMMIT=$TRAVIS_COMMIT -t humanconnection/frontend-nuxt .

after_success:
  - if [ $TRAVIS_BRANCH == "master" ] && [ $TRAVIS_EVENT_TYPE == "push" ]; then
    docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
    docker tag humanconnection/frontend-nuxt humanconnection/frontend-nuxt:alpha;
    docker push humanconnection/frontend-nuxt:alpha;
    fi
  - if [ $TRAVIS_BRANCH == "develop" ] && [ $TRAVIS_EVENT_TYPE == "push" ]; then
    docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
    docker tag humanconnection/frontend-nuxt humanconnection/frontend-nuxt:edge;
    docker push humanconnection/frontend-nuxt:edge;
    fi
