version: '3'

services:
  webapp:
    image: humanconnection/frontend-nuxt
    build:
      context: .
      args:
        BUILD_COMMIT: ${BUILD_COMMIT}
    stdin_open: true
    tty: true
    ports:
      - 3000:3000/tcp
